CREATE TABLE "long_term_observation_list_cycle2" (
	"id" serial PRIMARY KEY NOT NULL,
	"tdic_id" varchar(255),
	"source_id" varchar(255),
	"proposal_id" varchar(255),
	"proposal_no" varchar(255),
	"ep_db_object_id" varchar(255),
	"week_id" varchar(255),
	"pi" varchar(255),
	"group" varchar(255),
	"source_name" varchar(255),
	"obs_type" varchar(255),
	"ra" varchar(255),
	"dec" varchar(255),
	"total_exposure_time" varchar(255),
	"total_exposure_time_all" varchar(255),
	"exposure_time_unit" varchar(255),
	"continous_exposure" varchar(255),
	"visit_number" varchar(255),
	"exposure_per_vist_min" varchar(255),
	"exposure_per_vist_max" varchar(255),
	"completeness" varchar(255),
	"cadence" varchar(255),
	"cadence_unit" varchar(255),
	"precision" varchar(255),
	"precision_unit" varchar(255),
	"start_time" varchar(255),
	"end_time" varchar(255),
	"source_priority" varchar(255),
	"fxt1_window_mode" varchar(255),
	"fxt1_filter" varchar(255),
	"fxt2_window_mode" varchar(255),
	"fxt2_filter" varchar(255),
	"is_updated" varchar(255),
	"payload" varchar(255),
	"wxt_cmos" varchar(255),
	"wxt_cmos_x" varchar(255),
	"wxt_cmos_y" varchar(255),
	"fxt_cmr" varchar(255),
	"fxt_x" varchar(255),
	"fxt_y" varchar(255),
	"is_for_disrupted" varchar(255),
	"visible_days" varchar(255),
	"visible_date_ranges" varchar(255),
	"visible_range_count" varchar(255),
	"visible_total_days" varchar(255),
	"visible_date_ranges_only_sun" varchar(255),
	"visible_first_end" varchar(255),
	"visible_last_end" varchar(255),
	"mt_days" varchar(255),
	"left_mt_days" varchar(255),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "tootogp_schedule" ALTER COLUMN "earliest_start_time" SET DATA TYPE date;--> statement-breakpoint
ALTER TABLE "tootogp_schedule" ALTER COLUMN "planned_start_time" SET DATA TYPE date;--> statement-breakpoint
ALTER TABLE "tootogp_schedule" ALTER COLUMN "planned_end_time" SET DATA TYPE date;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "age" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "tootogp_schedule" ADD COLUMN "operator_name" varchar(255);