import { pgTable, integer, text, boolean, serial, varchar, unique, timestamp, date, doublePrecision, foreignKey } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const cycle1AntiTooProposal = pgTable("cycle1_anti_too_proposal", {
	proposalId: integer("proposal_id").primaryKey().notNull(),
	proposalNo: text("proposal_no"),
	no: integer(),
	piName: text("pi_name"),
	obsType: text("obs_type"),
	anticipatedToo: boolean("anticipated_too"),
	stp: integer(),
	category: text(),
	groupName: text("group_name"),
	observationsNumber: integer("observations_number"),
	totalExposureTime: integer("total_exposure_time"),
	exposureUnit: text("exposure_unit"),
	sourcePriority: text("source_priority"),
});

export const cycle2AntiTooProposal = pgTable("cycle2_anti_too_proposal", {
	proposalId: integer("proposal_id").primaryKey().notNull(),
	proposalNo: text("proposal_no"),
	no: integer(),
	piName: text("pi_name"),
	obsType: text("obs_type"),
	anticipatedToo: boolean("anticipated_too"),
	stp: integer(),
	category: text(),
	groupName: text("group_name"),
	observationsNumber: integer("observations_number"),
	totalExposureTime: integer("total_exposure_time"),
	exposureUnit: text("exposure_unit"),
	sourcePriority: text("source_priority"),
});

export const gpCycle1 = pgTable("gp_cycle1", {
	id: serial().primaryKey().notNull(),
	tdicId: varchar("tdic_id", { length: 255 }),
	sourceId: varchar("source_id", { length: 255 }),
	proposalId: varchar("proposal_id", { length: 255 }),
	proposalNo: varchar("proposal_no", { length: 255 }),
	pi: varchar({ length: 255 }),
	userGroup: varchar("user_group", { length: 255 }),
	sourceName: varchar("source_name", { length: 255 }),
	obsType: varchar("obs_type", { length: 255 }),
	ra: varchar({ length: 255 }),
	dec: varchar({ length: 255 }),
	totalExposureTime: varchar("total_exposure_time", { length: 255 }),
	exposureTimeUnit: varchar("exposure_time_unit", { length: 255 }),
	continousExposure: varchar("continous_exposure", { length: 255 }),
	visitNumber: varchar("visit_number", { length: 255 }),
	exposurePerVistMin: varchar("exposure_per_vist_min", { length: 255 }),
	exposurePerVistMax: varchar("exposure_per_vist_max", { length: 255 }),
	completeness: varchar({ length: 255 }),
	cadence: varchar({ length: 255 }),
	cadenceUnit: varchar("cadence_unit", { length: 255 }),
	precision: varchar({ length: 255 }),
	precisionUnit: varchar("precision_unit", { length: 255 }),
	startTime: varchar("start_time", { length: 255 }),
	endTime: varchar("end_time", { length: 255 }),
	sourcePriority: varchar("source_priority", { length: 255 }),
	fxt1WindowMode: varchar("fxt1_window_mode", { length: 255 }),
	fxt1Filter: varchar("fxt1_filter", { length: 255 }),
	fxt2WindowMode: varchar("fxt2_window_mode", { length: 255 }),
	fxt2Filter: varchar("fxt2_filter", { length: 255 }),
	isUpdated: varchar("is_updated", { length: 255 }),
});

export const gpCycle2 = pgTable("gp_cycle2", {
	id: serial().primaryKey().notNull(),
	tdicId: varchar("tdic_id", { length: 255 }),
	sourceId: varchar("source_id", { length: 255 }),
	proposalId: varchar("proposal_id", { length: 255 }),
	proposalNo: varchar("proposal_no", { length: 255 }),
	pi: varchar({ length: 255 }),
	userGroup: varchar("user_group", { length: 255 }),
	sourceName: varchar("source_name", { length: 255 }),
	obsType: varchar("obs_type", { length: 255 }),
	ra: varchar({ length: 255 }),
	dec: varchar({ length: 255 }),
	totalExposureTime: varchar("total_exposure_time", { length: 255 }),
	exposureTimeUnit: varchar("exposure_time_unit", { length: 255 }),
	continousExposure: varchar("continous_exposure", { length: 255 }),
	visitNumber: varchar("visit_number", { length: 255 }),
	exposurePerVistMin: varchar("exposure_per_vist_min", { length: 255 }),
	exposurePerVistMax: varchar("exposure_per_vist_max", { length: 255 }),
	completeness: varchar({ length: 255 }),
	cadence: varchar({ length: 255 }),
	cadenceUnit: varchar("cadence_unit", { length: 255 }),
	precision: varchar({ length: 255 }),
	precisionUnit: varchar("precision_unit", { length: 255 }),
	startTime: varchar("start_time", { length: 255 }),
	endTime: varchar("end_time", { length: 255 }),
	sourcePriority: varchar("source_priority", { length: 255 }),
	fxt1WindowMode: varchar("fxt1_window_mode", { length: 255 }),
	fxt1Filter: varchar("fxt1_filter", { length: 255 }),
	fxt2WindowMode: varchar("fxt2_window_mode", { length: 255 }),
	fxt2Filter: varchar("fxt2_filter", { length: 255 }),
	isUpdated: varchar("is_updated", { length: 255 }),
	anticipatedToo: varchar("anticipated_too", { length: 255 }),
	stp: varchar({ length: 255 }),
	category: varchar({ length: 255 }),
	type: varchar({ length: 255 }),
	payload: varchar({ length: 255 }).default('),
	wxtCmos: varchar("wxt_cmos", { length: 255 }).default('),
	cmosX: varchar("cmos_x", { length: 255 }).default('),
	cmosY: varchar("cmos_y", { length: 255 }).default('),
	fxtCmr: varchar("fxt_cmr", { length: 255 }).default('),
	cmrX: varchar("cmr_x", { length: 255 }).default('),
	cmrY: varchar("cmr_y", { length: 255 }).default('),
});

export const gpCycle2Proposal = pgTable("gp_cycle2_proposal", {
	id: serial().primaryKey().notNull(),
	no: varchar({ length: 255 }),
	proposalNo: varchar("proposal_no", { length: 255 }),
	pi: varchar({ length: 255 }),
	title: text(),
	stp: varchar({ length: 255 }),
	secondsR: varchar("seconds_r", { length: 255 }),
	obsType: varchar("obs_type", { length: 255 }),
	anticipatedToo: varchar("anticipated_too", { length: 255 }),
	userGroup: varchar("user_group", { length: 255 }),
	category: varchar({ length: 255 }),
	institution: varchar({ length: 255 }),
	ihepOrNaoc: varchar("ihep_or_naoc", { length: 255 }),
});

export const gsplist = pgTable("gsplist", {
	id: serial().primaryKey().notNull(),
	gspId: integer("gsp_id"),
	sspTime: text("ssp_time"),
	gspTime: text("gsp_time"),
	productionDate: text("production_date"),
}, (table) => [
	unique("gsplist_gsp_id_unique").on(table.gspId),
]);

export const obsAutoFollowup = pgTable("obs_auto_followup", {
	id: serial().primaryKey().notNull(),
	wpProducer: varchar("wp_producer", { length: 255 }),
	wpFilename: varchar("wp_filename", { length: 255 }),
	wpId: varchar("wp_id", { length: 255 }),
	wpType: varchar("wp_type", { length: 255 }),
	wpUrgency: varchar("wp_urgency", { length: 255 }),
	obsType: varchar("obs_type", { length: 255 }),
	obsIdNumber: varchar("obs_id_number", { length: 255 }),
	obtId: varchar("obt_id", { length: 255 }),
	epDbObjectId: varchar("ep_db_object_id", { length: 255 }),
	sourceName: varchar("source_name", { length: 255 }),
	rightAscension: varchar("right_ascension", { length: 255 }),
	declination: varchar({ length: 255 }),
	requestedObsDurationInSeconds: varchar("requested_obs_duration_in_seconds", { length: 255 }),
	userName: varchar("user_name", { length: 255 }),
	cmr: varchar({ length: 255 }),
	x: varchar({ length: 255 }),
	y: varchar({ length: 255 }),
	configParameterSwitch: varchar("config_parameter_switch", { length: 255 }),
	configForceSwitch: varchar("config_force_switch", { length: 255 }),
	operationCode3: varchar("operation_code3", { length: 255 }),
	minnsigmaDim: varchar("minnsigma_dim", { length: 255 }),
	snDim: varchar("sn_dim", { length: 255 }),
	snWindows: varchar("sn_windows", { length: 255 }),
	processSwitchA: varchar("process_switch_a", { length: 255 }),
	observationModeA: varchar("observation_mode_a", { length: 255 }),
	filterA: varchar("filter_a", { length: 255 }),
	processSwitchB: varchar("process_switch_b", { length: 255 }),
	observationModeB: varchar("observation_mode_b", { length: 255 }),
	filterB: varchar("filter_b", { length: 255 }),
	tcProgrammingMode: varchar("tc_programming_mode", { length: 255 }),
	startDate: varchar("start_date", { length: 255 }),
	endDate: varchar("end_date", { length: 255 }),
	obsGspIdStart: varchar("obs_gsp_id_start", { length: 255 }),
	obsGspIdEnd: varchar("obs_gsp_id_end", { length: 255 }),
	pointingDurationInOrbits: varchar("pointing_duration_in_orbits", { length: 255 }),
	pointingDurationInSeconds: varchar("pointing_duration_in_seconds", { length: 255 }),
	payloadRightAscension: varchar("payload_right_ascension", { length: 255 }),
	payloadDeclination: varchar("payload_declination", { length: 255 }),
	qc: varchar({ length: 255 }),
	q1: varchar({ length: 255 }),
	q2: varchar({ length: 255 }),
	q3: varchar({ length: 255 }),
	angZJ2000Rgrf: varchar("ang_z_j2000_rgrf", { length: 255 }),
	angXJ2000Rgrf: varchar("ang_x_j2000_rgrf", { length: 255 }),
	angYJ2000Rgrf: varchar("ang_y_j2000_rgrf", { length: 255 }),
	obsId: varchar("obs_id", { length: 255 }),
	proposalId: varchar("proposal_id", { length: 255 }),
	sourceId: varchar("source_id", { length: 255 }),
	mainType: varchar("main_type", { length: 255 }),
	subPriority: varchar("sub_priority", { length: 255 }),
});

export const users = pgTable("users", {
	id: integer().primaryKey().generatedAlwaysAsIdentity({ name: "users_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 2147483647, cache: 1 }),
	name: varchar({ length: 255 }).notNull(),
	age: integer().default(0).notNull(),
	email: varchar({ length: 255 }).notNull(),
	vip: boolean().default(false).notNull(),
	username: varchar({ length: 255 }).notNull(),
	passwordHash: text("password_hash").default(').notNull(),
}, (table) => [
	unique("users_email_unique").on(table.email),
	unique("users_username_unique").on(table.username),
]);

export const tooReq = pgTable("too_req", {
	id: integer().primaryKey().generatedAlwaysAsIdentity({ name: "too_req_id_seq", startWith: 1, increment: 1, minValue: 1, maxValue: 2147483647, cache: 1 }),
	requestFilename: varchar("request_filename", { length: 255 }),
	requestDate: varchar("request_date", { length: 255 }),
	requestUrgency: varchar("request_urgency", { length: 255 }),
	obsType: varchar("obs_type", { length: 255 }),
	epDbObjectId: varchar("ep_db_object_id", { length: 255 }),
	sourceName: varchar("source_name", { length: 255 }),
	rightAscension: varchar("right_ascension", { length: 255 }),
	declination: varchar({ length: 255 }),
	requestedObsDurationInSeconds: integer("requested_obs_duration_in_seconds").default(0).notNull(),
	requestedObsDurationInOrbits: integer("requested_obs_duration_in_orbits").default(0).notNull(),
	userName: varchar("user_name", { length: 255 }),
	userGroup: varchar("user_group", { length: 255 }),
	cmr: varchar({ length: 255 }),
	x: varchar({ length: 255 }),
	y: varchar({ length: 255 }),
	processSwitchA: varchar("process_switch_a", { length: 255 }),
	observationModeA: varchar("observation_mode_a", { length: 255 }),
	filterA: varchar("filter_a", { length: 255 }),
	processSwitchB: varchar("process_switch_b", { length: 255 }),
	observationModeB: varchar("observation_mode_b", { length: 255 }),
	filterB: varchar("filter_b", { length: 255 }),
	obsPriority: varchar("obs_priority", { length: 255 }),
	timeConstraints: varchar("time_constraints", { length: 255 }),
	sourceId: integer("source_id").default(0).notNull(),
	proposalId: integer("proposal_id").default(0).notNull(),
	proposalNo: integer("proposal_no").default(0).notNull(),
	toGp: boolean("to_gp").default(false).notNull(),
});

export const obslogtest = pgTable("obslogtest", {
	obsIdHex: text("obs_id_hex").primaryKey().notNull(),
	obsId: text("obs_id"),
	startTime: timestamp("start_time", { mode: 'string' }),
	endTime: timestamp("end_time", { mode: 'string' }),
	validSecs: integer("valid_secs"),
	status: text(),
	file002A: text("file_002a"),
	file0260: text("file_0260"),
});

export const obsWp = pgTable("obs_wp", {
	id: serial().primaryKey().notNull(),
	wpProducer: varchar("wp_producer", { length: 255 }),
	wpFilename: varchar("wp_filename", { length: 255 }),
	wpId: varchar("wp_id", { length: 255 }),
	wpType: varchar("wp_type", { length: 255 }),
	wpUrgency: varchar("wp_urgency", { length: 255 }),
	obsType: varchar("obs_type", { length: 255 }),
	obsIdNumber: varchar("obs_id_number", { length: 255 }),
	obtId: varchar("obt_id", { length: 255 }),
	epDbObjectId: varchar("ep_db_object_id", { length: 255 }),
	sourceName: varchar("source_name", { length: 255 }),
	rightAscension: varchar("right_ascension", { length: 255 }),
	declination: varchar({ length: 255 }),
	requestedObsDurationInSeconds: varchar("requested_obs_duration_in_seconds", { length: 255 }),
	userName: varchar("user_name", { length: 255 }),
	cmr: varchar({ length: 255 }),
	x: varchar({ length: 255 }),
	y: varchar({ length: 255 }),
	configParameterSwitch: varchar("config_parameter_switch", { length: 255 }),
	configForceSwitch: varchar("config_force_switch", { length: 255 }),
	operationCode3: varchar("operation_code3", { length: 255 }),
	minnsigmaDim: varchar("minnsigma_dim", { length: 255 }),
	snDim: varchar("sn_dim", { length: 255 }),
	snWindows: varchar("sn_windows", { length: 255 }),
	processSwitchA: varchar("process_switch_a", { length: 255 }),
	observationModeA: varchar("observation_mode_a", { length: 255 }),
	filterA: varchar("filter_a", { length: 255 }),
	processSwitchB: varchar("process_switch_b", { length: 255 }),
	observationModeB: varchar("observation_mode_b", { length: 255 }),
	filterB: varchar("filter_b", { length: 255 }),
	tcProgrammingMode: varchar("tc_programming_mode", { length: 255 }),
	startDate: varchar("start_date", { length: 255 }),
	endDate: varchar("end_date", { length: 255 }),
	obsGspIdStart: varchar("obs_gsp_id_start", { length: 255 }),
	obsGspIdEnd: varchar("obs_gsp_id_end", { length: 255 }),
	pointingDurationInOrbits: varchar("pointing_duration_in_orbits", { length: 255 }),
	pointingDurationInSeconds: varchar("pointing_duration_in_seconds", { length: 255 }),
	payloadRightAscension: varchar("payload_right_ascension", { length: 255 }),
	payloadDeclination: varchar("payload_declination", { length: 255 }),
	qc: varchar({ length: 255 }),
	q1: varchar({ length: 255 }),
	q2: varchar({ length: 255 }),
	q3: varchar({ length: 255 }),
	angZJ2000Rgrf: varchar("ang_z_j2000_rgrf", { length: 255 }),
	angXJ2000Rgrf: varchar("ang_x_j2000_rgrf", { length: 255 }),
	angYJ2000Rgrf: varchar("ang_y_j2000_rgrf", { length: 255 }),
	obsId: varchar("obs_id", { length: 255 }),
	proposalId: varchar("proposal_id", { length: 255 }),
	sourceId: varchar("source_id", { length: 255 }),
	mainType: varchar("main_type", { length: 255 }),
	relatedProposalId1: varchar("related_proposal_id1", { length: 255 }),
	relatedProposalId2: varchar("related_proposal_id2", { length: 255 }),
	relatedProposalId3: varchar("related_proposal_id3", { length: 255 }),
	subPriority: varchar("sub_priority", { length: 255 }),
});

export const observations = pgTable("observations", {
	id: serial().primaryKey().notNull(),
	obsType: varchar("obs_type", { length: 255 }),
	obsIdNumber: varchar("obs_id_number", { length: 255 }),
	obtId: varchar("obt_id", { length: 255 }),
	epDbObjectId: varchar("ep_db_object_id", { length: 255 }),
	sourceName: varchar("source_name", { length: 255 }),
	rightAscension: varchar("right_ascension", { length: 255 }),
	declination: varchar({ length: 255 }),
	requestedObsDurationInSeconds: varchar("requested_obs_duration_in_seconds", { length: 255 }),
	userName: varchar("user_name", { length: 255 }),
	cmr: varchar({ length: 255 }),
	x: varchar({ length: 255 }),
	y: varchar({ length: 255 }),
	configParameterSwitch: varchar("config_parameter_switch", { length: 255 }),
	configForceSwitch: varchar("config_force_switch", { length: 255 }),
	operationCode3: varchar("operation_code3", { length: 255 }),
	minnsigmaDim: varchar("minnsigma_dim", { length: 255 }),
	snDim: varchar("sn_dim", { length: 255 }),
	snWindows: varchar("sn_windows", { length: 255 }),
	processSwitchA: varchar("process_switch_a", { length: 255 }),
	observationModeA: varchar("observation_mode_a", { length: 255 }),
	filterA: varchar("filter_a", { length: 255 }),
	processSwitchB: varchar("process_switch_b", { length: 255 }),
	observationModeB: varchar("observation_mode_b", { length: 255 }),
	filterB: varchar("filter_b", { length: 255 }),
	tcProgrammingMode: varchar("tc_programming_mode", { length: 255 }),
	startDate: varchar("start_date", { length: 255 }),
	endDate: varchar("end_date", { length: 255 }),
	obsGspIdStart: varchar("obs_gsp_id_start", { length: 255 }),
	obsGspIdEnd: varchar("obs_gsp_id_end", { length: 255 }),
	pointingDurationInOrbits: varchar("pointing_duration_in_orbits", { length: 255 }),
	pointingDurationInSeconds: varchar("pointing_duration_in_seconds", { length: 255 }),
	payloadRightAscension: varchar("payload_right_ascension", { length: 255 }),
	payloadDeclination: varchar("payload_declination", { length: 255 }),
	qc: varchar({ length: 255 }),
	q1: varchar({ length: 255 }),
	q2: varchar({ length: 255 }),
	q3: varchar({ length: 255 }),
	angZJ2000Rgrf: varchar("ang_z_j2000_rgrf", { length: 255 }),
	angXJ2000Rgrf: varchar("ang_x_j2000_rgrf", { length: 255 }),
	angYJ2000Rgrf: varchar("ang_y_j2000_rgrf", { length: 255 }),
});

export const obslog = pgTable("obslog", {
	obsIdHex: text("obs_id_hex").notNull(),
	obsId: text("obs_id").notNull(),
	startTime: timestamp("start_time", { mode: 'string' }),
	endTime: timestamp("end_time", { mode: 'string' }),
	status: varchar({ length: 11 }),
	validSecs: integer("valid_secs"),
}, (table) => [
	unique("unique_obs_id_hex").on(table.obsIdHex),
]);

export const reqTest = pgTable("req_test", {
	id: serial().primaryKey().notNull(),
	requestFilename: varchar("request_filename", { length: 255 }),
	requestDate: varchar("request_date", { length: 255 }),
	requestUrgency: varchar("request_urgency", { length: 255 }),
	obsType: varchar("obs_type", { length: 255 }),
	epDbObjectId: varchar("ep_db_object_id", { length: 255 }),
	sourceName: varchar("source_name", { length: 255 }),
	rightAscension: varchar("right_ascension", { length: 255 }),
	declination: varchar({ length: 255 }),
	requestedObsDurationInSeconds: varchar("requested_obs_duration_in_seconds", { length: 255 }),
	requestedObsDurationInOrbits: varchar("requested_obs_duration_in_orbits", { length: 255 }),
	userName: varchar("user_name", { length: 255 }),
	userGroup: varchar("user_group", { length: 255 }),
	cmr: varchar({ length: 255 }),
	x: varchar({ length: 255 }),
	y: varchar({ length: 255 }),
	processSwitchA: varchar("process_switch_a", { length: 255 }),
	observationModeA: varchar("observation_mode_a", { length: 255 }),
	filterA: varchar("filter_a", { length: 255 }),
	processSwitchB: varchar("process_switch_b", { length: 255 }),
	observationModeB: varchar("observation_mode_b", { length: 255 }),
	filterB: varchar("filter_b", { length: 255 }),
	obsPriority: varchar("obs_priority", { length: 255 }),
	timeConstraints: varchar("time_constraints", { length: 255 }),
	sourceId: varchar("source_id", { length: 255 }),
	proposalId: varchar("proposal_id", { length: 255 }),
	proposalNo: varchar("proposal_no", { length: 255 }),
});

export const sPassplan = pgTable("s_passplan", {
	id: serial().primaryKey().notNull(),
	taskid: integer(),
	facilityid: varchar({ length: 100 }),
	orbitcircle: integer(),
	starttime: varchar({ length: 50 }),
	endtime: varchar({ length: 50 }),
	plantype: varchar({ length: 50 }),
}, (table) => [
	unique("s_passplan_orbitcircle_key").on(table.orbitcircle),
]);

export const saa = pgTable("saa", {
	id: serial().primaryKey().notNull(),
	orbitid: integer(),
	begintime: varchar({ length: 50 }),
	endtime: varchar({ length: 50 }),
}, (table) => [
	unique("saa_begintime_key").on(table.begintime),
]);

export const wxteffdaily = pgTable("wxteffdaily", {
	recordDate: date("record_date").primaryKey().notNull(),
	wxtStatus01Count: integer("wxt_status_01_count"),
	wxtStatus02Count: integer("wxt_status_02_count"),
	wxtStatus03Count: integer("wxt_status_03_count"),
	wxtStatus04Count: integer("wxt_status_04_count"),
	wxtStatus05Count: integer("wxt_status_05_count"),
	wxtStatus06Count: integer("wxt_status_06_count"),
	wxtStatus07Count: integer("wxt_status_07_count"),
	wxtStatus08Count: integer("wxt_status_08_count"),
	wxtStatus09Count: integer("wxt_status_09_count"),
	wxtStatus10Count: integer("wxt_status_10_count"),
	wxtStatus11Count: integer("wxt_status_11_count"),
	wxtStatus12Count: integer("wxt_status_12_count"),
});

export const xPassplan = pgTable("x_passplan", {
	id: serial().primaryKey().notNull(),
	recvid: integer(),
	priority: varchar({ length: 50 }),
	orbitid: integer(),
	downloadmode: integer(),
	transrate: doublePrecision(),
	channelid: integer(),
	sensorid: integer(),
	receivingstation: varchar({ length: 100 }),
	arrivetime: varchar({ length: 50 }),
	leavetime: varchar({ length: 50 }),
	begintime: varchar({ length: 50 }),
	endtime: varchar({ length: 50 }),
}, (table) => [
	unique("x_passplan_orbitid_key").on(table.orbitid),
]);

export const approvedToo = pgTable("approved_too", {
	id: serial().primaryKey().notNull(),
	"0310KeVFlux": varchar("0.3-10_keV_Flux", { length: 255 }),
	completeness: varchar({ length: 255 }),
	continuousExposure: varchar("continuous_exposure", { length: 255 }),
	epscProposal: boolean("epsc_proposal"),
	epDbObjectId: varchar("ep_db_object_id", { length: 255 }),
	fxtCmr: varchar("fxt_cmr", { length: 255 }),
	fxtX: varchar("fxt_x", { length: 255 }),
	fxtY: varchar("fxt_y", { length: 255 }),
	payload: varchar({ length: 255 }),
	receivedTime: timestamp("received_time", { withTimezone: true, mode: 'string' }),
	requestNumberOfVisits: integer("request_number_of_visits"),
	requestRestrainedBeginTime: timestamp("request_restrained_begin_time", { withTimezone: true, mode: 'string' }),
	requestRestrainedEndTime: timestamp("request_restrained_end_time", { withTimezone: true, mode: 'string' }),
	requestSingleExposureTime: integer("request_single_exposure_time"),
	requestTotalExposureTime: integer("request_total_exposure_time"),
	requestUrgencyOfObservation: varchar("request_urgency_of_observation", { length: 255 }),
	requestCadence: integer("request_cadence"),
	requestCadenceUnit: varchar("request_cadence_unit", { length: 255 }),
	reviewedNumberOfVisits: varchar("reviewed_number_of_visits", { length: 255 }),
	reviewedScientificImportance: varchar("reviewed_scientific_importance", { length: 255 }),
	reviewedSingleExposureTime: varchar("reviewed_single_exposure_time", { length: 255 }),
	reviewedTotalExposureTime: varchar("reviewed_total_exposure_time", { length: 255 }),
	reviewedUrgencyOfObservation: varchar("reviewed_urgency_of_observation", { length: 255 }),
	reviewedCadence: varchar("reviewed_cadence", { length: 255 }),
	reviewedCadenceUnit: varchar("reviewed_cadence_unit", { length: 255 }),
	reviewedTime: timestamp("reviewed_time", { withTimezone: true, mode: 'string' }),
	stp: varchar({ length: 255 }),
	sourceType: varchar("source_type", { length: 255 }),
	vBandMagnitude: varchar("v_band_magnitude", { length: 255 }),
	wxtCmos: varchar("wxt_cmos", { length: 255 }),
	wxtCmosX: varchar("wxt_cmos_x", { length: 255 }),
	wxtCmosY: varchar("wxt_cmos_y", { length: 255 }),
	dec: varchar({ length: 255 }),
	exposureTimeUnit: varchar("exposure_time_unit", { length: 255 }),
	fxt1Filter: varchar("fxt1_filter", { length: 255 }),
	fxt1WindowMode: varchar("fxt1_window_mode", { length: 255 }),
	fxt2Filter: varchar("fxt2_filter", { length: 255 }),
	fxt2WindowMode: varchar("fxt2_window_mode", { length: 255 }),
	group: varchar({ length: 255 }),
	pi: varchar({ length: 255 }),
	proposalId: varchar("proposal_id", { length: 255 }),
	proposalNo: varchar("proposal_no", { length: 255 }),
	ra: varchar({ length: 255 }),
	sourceId: varchar("source_id", { length: 255 }),
	sourceName: varchar("source_name", { length: 255 }),
	type: varchar({ length: 255 }),
});

export const tootogpSchedule = pgTable("tootogp_schedule", {
	id: serial().primaryKey().notNull(),
	approvedTooId: integer("approved_too_id").notNull(),
	parentEpDbObjectId: varchar("parent_ep_db_object_id", { length: 255 }).notNull(),
	generatedEpDbObjectId: varchar("generated_ep_db_object_id", { length: 255 }).notNull(),
	sequenceNo: integer("sequence_no").notNull(),
	earliestStartTime: date("earliest_start_time"),
	plannedStartTime: date("planned_start_time"),
	plannedEndTime: date("planned_end_time"),
	cadenceValue: integer("cadence_value"),
	cadenceUnit: varchar("cadence_unit", { length: 32 }),
	reviewedNumberOfVisitsSnapshot: integer("reviewed_number_of_visits_snapshot"),
	reviewedSingleExposureTimeSnapshot: integer("reviewed_single_exposure_time_snapshot"),
	reviewedTotalExposureTimeSnapshot: integer("reviewed_total_exposure_time_snapshot"),
	status: varchar({ length: 32 }).default('planned').notNull(),
	notes: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	operatorName: varchar("operator_name", { length: 255 }),
}, (table) => [
	foreignKey({
			columns: [table.approvedTooId],
			foreignColumns: [approvedToo.id],
			name: "tootogp_schedule_approved_too_id_approved_too_id_fk"
		}),
	unique("tootogp_schedule_generated_ep_db_object_id_unique").on(table.generatedEpDbObjectId),
	unique("tootogp_schedule_parent_sequence_unique").on(table.sequenceNo, table.approvedTooId),
]);

export const longTermObservationListCycle2 = pgTable("long_term_observation_list_cycle2", {
	id: serial().primaryKey().notNull(),
	tdicId: varchar("tdic_id", { length: 255 }),
	sourceId: varchar("source_id", { length: 255 }),
	proposalId: varchar("proposal_id", { length: 255 }),
	proposalNo: varchar("proposal_no", { length: 255 }),
	epDbObjectId: varchar("ep_db_object_id", { length: 255 }),
	weekId: varchar("week_id", { length: 255 }),
	pi: varchar({ length: 255 }),
	group: varchar({ length: 255 }),
	sourceName: varchar("source_name", { length: 255 }),
	obsType: varchar("obs_type", { length: 255 }),
	ra: varchar({ length: 255 }),
	dec: varchar({ length: 255 }),
	totalExposureTime: varchar("total_exposure_time", { length: 255 }),
	totalExposureTimeAll: varchar("total_exposure_time_all", { length: 255 }),
	exposureTimeUnit: varchar("exposure_time_unit", { length: 255 }),
	continousExposure: varchar("continous_exposure", { length: 255 }),
	visitNumber: varchar("visit_number", { length: 255 }),
	exposurePerVistMin: varchar("exposure_per_vist_min", { length: 255 }),
	exposurePerVistMax: varchar("exposure_per_vist_max", { length: 255 }),
	completeness: varchar({ length: 255 }),
	cadence: varchar({ length: 255 }),
	cadenceUnit: varchar("cadence_unit", { length: 255 }),
	precision: varchar({ length: 255 }),
	precisionUnit: varchar("precision_unit", { length: 255 }),
	startTime: varchar("start_time", { length: 255 }),
	endTime: varchar("end_time", { length: 255 }),
	sourcePriority: varchar("source_priority", { length: 255 }),
	fxt1WindowMode: varchar("fxt1_window_mode", { length: 255 }),
	fxt1Filter: varchar("fxt1_filter", { length: 255 }),
	fxt2WindowMode: varchar("fxt2_window_mode", { length: 255 }),
	fxt2Filter: varchar("fxt2_filter", { length: 255 }),
	isUpdated: varchar("is_updated", { length: 255 }),
	payload: varchar({ length: 255 }),
	wxtCmos: varchar("wxt_cmos", { length: 255 }),
	wxtCmosX: varchar("wxt_cmos_x", { length: 255 }),
	wxtCmosY: varchar("wxt_cmos_y", { length: 255 }),
	fxtCmr: varchar("fxt_cmr", { length: 255 }),
	fxtX: varchar("fxt_x", { length: 255 }),
	fxtY: varchar("fxt_y", { length: 255 }),
	isForDisrupted: varchar("is_for_disrupted", { length: 255 }),
	visibleDays: varchar("visible_days", { length: 255 }),
	visibleDateRanges: varchar("visible_date_ranges", { length: 255 }),
	visibleRangeCount: varchar("visible_range_count", { length: 255 }),
	visibleTotalDays: varchar("visible_total_days", { length: 255 }),
	visibleDateRangesOnlySun: varchar("visible_date_ranges_only_sun", { length: 255 }),
	visibleFirstEnd: varchar("visible_first_end", { length: 255 }),
	visibleLastEnd: varchar("visible_last_end", { length: 255 }),
	mtDays: varchar("mt_days", { length: 255 }),
	leftMtDays: varchar("left_mt_days", { length: 255 }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});
