import { boolean, integer, pgTable, varchar, serial, text, timestamp, unique, doublePrecision, date } from "drizzle-orm/pg-core";

export const usersTable = pgTable("users", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  name: varchar({ length: 255 }).notNull(),
	username: varchar({ length: 255 }).notNull().unique(),
  age: integer().notNull(),
  email: varchar({ length: 255 }).notNull().unique(),
	passwordHash: text("password_hash").notNull().default(""),
  vip: boolean().notNull().default(false),
});

export const tooReqTable = pgTable("too_req", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  request_filename: varchar({ length: 255 }),
  request_date: varchar({ length: 255 }),
  request_urgency: varchar({ length: 255 }),
  obs_type: varchar({ length: 255 }),
  ep_db_object_id: varchar({ length: 255 }),
  source_name: varchar({ length: 255 }),
  right_ascension: varchar({ length: 255 }),
  declination: varchar({ length: 255 }),
  requested_obs_duration_in_seconds: integer().notNull().default(0),
  requested_obs_duration_in_orbits: integer().notNull().default(0),
  user_name: varchar({ length: 255 }),
  user_group: varchar({ length: 255 }),
  cmr: varchar({ length: 255 }),
  x: varchar({ length: 255 }),
  y: varchar({ length: 255 }),
  process_switch_a: varchar({ length: 255 }),
  observation_mode_a: varchar({ length: 255 }),
  filter_a: varchar({ length: 255 }),
  process_switch_b: varchar({ length: 255 }),
  observation_mode_b: varchar({ length: 255 }),
  filter_b: varchar({ length: 255 }),
  obs_priority: varchar({ length: 255 }),
  time_constraints: varchar({ length: 255 }),
  source_id: integer().notNull().default(0),
  proposal_id: integer().notNull().default(0),
  proposal_no: integer().notNull().default(0),
  to_gp: boolean().notNull().default(false),
});


export const observations = pgTable("observations", {
	id: serial().primaryKey().notNull(),
	obsType: varchar("obs_type", { length: 255 }),
	obsIdNumber: varchar("obs_id_number", { length: 255 }),
	obtId: varchar("obt_id", { length: 255 }),
	epDbObjectId: varchar("ep_db_object_id", { length: 255 }),
	sourceName: varchar("source_name", { length: 255 }),
	rightAscension: varchar("right_ascension", { length: 255 }),
	declination: varchar({ length: 255 }),
	requestedObsDurationInSeconds: varchar("requested_obs_duration_in_seconds", { length: 255 }),
	userName: varchar("user_name", { length: 255 }),
	cmr: varchar({ length: 255 }),
	x: varchar({ length: 255 }),
	y: varchar({ length: 255 }),
	configParameterSwitch: varchar("config_parameter_switch", { length: 255 }),
	configForceSwitch: varchar("config_force_switch", { length: 255 }),
	operationCode3: varchar("operation_code3", { length: 255 }),
	minnsigmaDim: varchar("minnsigma_dim", { length: 255 }),
	snDim: varchar("sn_dim", { length: 255 }),
	snWindows: varchar("sn_windows", { length: 255 }),
	processSwitchA: varchar("process_switch_a", { length: 255 }),
	observationModeA: varchar("observation_mode_a", { length: 255 }),
	filterA: varchar("filter_a", { length: 255 }),
	processSwitchB: varchar("process_switch_b", { length: 255 }),
	observationModeB: varchar("observation_mode_b", { length: 255 }),
	filterB: varchar("filter_b", { length: 255 }),
	tcProgrammingMode: varchar("tc_programming_mode", { length: 255 }),
	startDate: varchar("start_date", { length: 255 }),
	endDate: varchar("end_date", { length: 255 }),
	obsGspIdStart: varchar("obs_gsp_id_start", { length: 255 }),
	obsGspIdEnd: varchar("obs_gsp_id_end", { length: 255 }),
	pointingDurationInOrbits: varchar("pointing_duration_in_orbits", { length: 255 }),
	pointingDurationInSeconds: varchar("pointing_duration_in_seconds", { length: 255 }),
	payloadRightAscension: varchar("payload_right_ascension", { length: 255 }),
	payloadDeclination: varchar("payload_declination", { length: 255 }),
	qc: varchar({ length: 255 }),
	q1: varchar({ length: 255 }),
	q2: varchar({ length: 255 }),
	q3: varchar({ length: 255 }),
	angZJ2000Rgrf: varchar("ang_z_j2000_rgrf", { length: 255 }),
	angXJ2000Rgrf: varchar("ang_x_j2000_rgrf", { length: 255 }),
	angYJ2000Rgrf: varchar("ang_y_j2000_rgrf", { length: 255 }),
});

export const cycle2AntiTooProposal = pgTable("cycle2_anti_too_proposal", {
	proposalId: integer("proposal_id").primaryKey().notNull(),
	proposalNo: text("proposal_no"),
	no: integer(),
	piName: text("pi_name"),
	obsType: text("obs_type"),
	anticipatedToo: boolean("anticipated_too"),
	stp: integer(),
	category: text(),
	groupName: text("group_name"),
	observationsNumber: integer("observations_number"),
	totalExposureTime: integer("total_exposure_time"),
	exposureUnit: text("exposure_unit"),
	sourcePriority: text("source_priority"),
});

export const obsWp = pgTable("obs_wp", {
	id: serial().primaryKey().notNull(),
	wpProducer: varchar("wp_producer", { length: 255 }),
	wpFilename: varchar("wp_filename", { length: 255 }),
	wpId: varchar("wp_id", { length: 255 }),
	wpType: varchar("wp_type", { length: 255 }),
	wpUrgency: varchar("wp_urgency", { length: 255 }),
	obsType: varchar("obs_type", { length: 255 }),
	obsIdNumber: varchar("obs_id_number", { length: 255 }),
	obtId: varchar("obt_id", { length: 255 }),
	epDbObjectId: varchar("ep_db_object_id", { length: 255 }),
	sourceName: varchar("source_name", { length: 255 }),
	rightAscension: varchar("right_ascension", { length: 255 }),
	declination: varchar({ length: 255 }),
	requestedObsDurationInSeconds: varchar("requested_obs_duration_in_seconds", { length: 255 }),
	userName: varchar("user_name", { length: 255 }),
	cmr: varchar({ length: 255 }),
	x: varchar({ length: 255 }),
	y: varchar({ length: 255 }),
	configParameterSwitch: varchar("config_parameter_switch", { length: 255 }),
	configForceSwitch: varchar("config_force_switch", { length: 255 }),
	operationCode3: varchar("operation_code3", { length: 255 }),
	minnsigmaDim: varchar("minnsigma_dim", { length: 255 }),
	snDim: varchar("sn_dim", { length: 255 }),
	snWindows: varchar("sn_windows", { length: 255 }),
	processSwitchA: varchar("process_switch_a", { length: 255 }),
	observationModeA: varchar("observation_mode_a", { length: 255 }),
	filterA: varchar("filter_a", { length: 255 }),
	processSwitchB: varchar("process_switch_b", { length: 255 }),
	observationModeB: varchar("observation_mode_b", { length: 255 }),
	filterB: varchar("filter_b", { length: 255 }),
	tcProgrammingMode: varchar("tc_programming_mode", { length: 255 }),
	startDate: varchar("start_date", { length: 255 }),
	endDate: varchar("end_date", { length: 255 }),
	obsGspIdStart: varchar("obs_gsp_id_start", { length: 255 }),
	obsGspIdEnd: varchar("obs_gsp_id_end", { length: 255 }),
	pointingDurationInOrbits: varchar("pointing_duration_in_orbits", { length: 255 }),
	pointingDurationInSeconds: varchar("pointing_duration_in_seconds", { length: 255 }),
	payloadRightAscension: varchar("payload_right_ascension", { length: 255 }),
	payloadDeclination: varchar("payload_declination", { length: 255 }),
	qc: varchar({ length: 255 }),
	q1: varchar({ length: 255 }),
	q2: varchar({ length: 255 }),
	q3: varchar({ length: 255 }),
	angZJ2000Rgrf: varchar("ang_z_j2000_rgrf", { length: 255 }),
	angXJ2000Rgrf: varchar("ang_x_j2000_rgrf", { length: 255 }),
	angYJ2000Rgrf: varchar("ang_y_j2000_rgrf", { length: 255 }),
	obsId: varchar("obs_id", { length: 255 }),
	proposalId: varchar("proposal_id", { length: 255 }),
	sourceId: varchar("source_id", { length: 255 }),
	mainType: varchar("main_type", { length: 255 }),
	relatedProposalId1: varchar("related_proposal_id1", { length: 255 }),
	relatedProposalId2: varchar("related_proposal_id2", { length: 255 }),
	relatedProposalId3: varchar("related_proposal_id3", { length: 255 }),
	subPriority: varchar("sub_priority", { length: 255 }),
});

export const gsplist = pgTable("gsplist", {
	id: serial().primaryKey().notNull(),
	gspId: integer("gsp_id"),
	sspTime: text("ssp_time"),
	gspTime: text("gsp_time"),
	productionDate: text("production_date"),
}, (table) => [
	unique("gsplist_gsp_id_unique").on(table.gspId),
]);

export const obslogtest = pgTable("obslogtest", {
	obsIdHex: text("obs_id_hex").primaryKey().notNull(),
	obsId: text("obs_id"),
	startTime: timestamp("start_time", { mode: 'string' }),
	endTime: timestamp("end_time", { mode: 'string' }),
	validSecs: integer("valid_secs"),
	status: text(),
	file002A: text("file_002a"),
	file0260: text("file_0260"),
});

export const xPassplan = pgTable("x_passplan", {
	id: serial().primaryKey().notNull(),
	recvid: integer(),
	priority: varchar({ length: 50 }),
	orbitid: integer(),
	downloadmode: integer(),
	transrate: doublePrecision(),
	channelid: integer(),
	sensorid: integer(),
	receivingstation: varchar({ length: 100 }),
	arrivetime: varchar({ length: 50 }),
	leavetime: varchar({ length: 50 }),
	begintime: varchar({ length: 50 }),
	endtime: varchar({ length: 50 }),
}, (table) => [
	unique("x_passplan_orbitid_key").on(table.orbitid),
]);

export const saa = pgTable("saa", {
	id: serial().primaryKey().notNull(),
	orbitid: integer(),
	begintime: varchar({ length: 50 }),
	endtime: varchar({ length: 50 }),
}, (table) => [
	unique("saa_begintime_key").on(table.begintime),
]);

export const obslog = pgTable("obslog", {
	obsIdHex: text("obs_id_hex").notNull(),
	obsId: text("obs_id").notNull(),
	startTime: timestamp("start_time", { mode: 'string' }),
	endTime: timestamp("end_time", { mode: 'string' }),
	status: varchar({ length: 11 }),
	validSecs: integer("valid_secs"),
}, (table) => [
	unique("unique_obs_id_hex").on(table.obsIdHex),
]);

export const reqTest = pgTable("req_test", {
	id: serial().primaryKey().notNull(),
	requestFilename: varchar("request_filename", { length: 255 }),
	requestDate: varchar("request_date", { length: 255 }),
	requestUrgency: varchar("request_urgency", { length: 255 }),
	obsType: varchar("obs_type", { length: 255 }),
	epDbObjectId: varchar("ep_db_object_id", { length: 255 }),
	sourceName: varchar("source_name", { length: 255 }),
	rightAscension: varchar("right_ascension", { length: 255 }),
	declination: varchar({ length: 255 }),
	requestedObsDurationInSeconds: varchar("requested_obs_duration_in_seconds", { length: 255 }),
	requestedObsDurationInOrbits: varchar("requested_obs_duration_in_orbits", { length: 255 }),
	userName: varchar("user_name", { length: 255 }),
	userGroup: varchar("user_group", { length: 255 }),
	cmr: varchar({ length: 255 }),
	x: varchar({ length: 255 }),
	y: varchar({ length: 255 }),
	processSwitchA: varchar("process_switch_a", { length: 255 }),
	observationModeA: varchar("observation_mode_a", { length: 255 }),
	filterA: varchar("filter_a", { length: 255 }),
	processSwitchB: varchar("process_switch_b", { length: 255 }),
	observationModeB: varchar("observation_mode_b", { length: 255 }),
	filterB: varchar("filter_b", { length: 255 }),
	obsPriority: varchar("obs_priority", { length: 255 }),
	timeConstraints: varchar("time_constraints", { length: 255 }),
	sourceId: varchar("source_id", { length: 255 }),
	proposalId: varchar("proposal_id", { length: 255 }),
	proposalNo: varchar("proposal_no", { length: 255 }),
});

export const sPassplan = pgTable("s_passplan", {
	id: serial().primaryKey().notNull(),
	taskid: integer(),
	facilityid: varchar({ length: 100 }),
	orbitcircle: integer(),
	starttime: varchar({ length: 50 }),
	endtime: varchar({ length: 50 }),
	plantype: varchar({ length: 50 }),
}, (table) => [
	unique("s_passplan_orbitcircle_key").on(table.orbitcircle),
]);

export const gpCycle1 = pgTable("gp_cycle1", {
	id: serial().primaryKey().notNull(),
	tdicId: varchar("tdic_id", { length: 255 }),
	sourceId: varchar("source_id", { length: 255 }),
	proposalId: varchar("proposal_id", { length: 255 }),
	proposalNo: varchar("proposal_no", { length: 255 }),
	pi: varchar({ length: 255 }),
	userGroup: varchar("user_group", { length: 255 }),
	sourceName: varchar("source_name", { length: 255 }),
	obsType: varchar("obs_type", { length: 255 }),
	ra: varchar({ length: 255 }),
	dec: varchar({ length: 255 }),
	totalExposureTime: varchar("total_exposure_time", { length: 255 }),
	exposureTimeUnit: varchar("exposure_time_unit", { length: 255 }),
	continousExposure: varchar("continous_exposure", { length: 255 }),
	visitNumber: varchar("visit_number", { length: 255 }),
	exposurePerVistMin: varchar("exposure_per_vist_min", { length: 255 }),
	exposurePerVistMax: varchar("exposure_per_vist_max", { length: 255 }),
	completeness: varchar({ length: 255 }),
	cadence: varchar({ length: 255 }),
	cadenceUnit: varchar("cadence_unit", { length: 255 }),
	precision: varchar({ length: 255 }),
	precisionUnit: varchar("precision_unit", { length: 255 }),
	startTime: varchar("start_time", { length: 255 }),
	endTime: varchar("end_time", { length: 255 }),
	sourcePriority: varchar("source_priority", { length: 255 }),
	fxt1WindowMode: varchar("fxt1_window_mode", { length: 255 }),
	fxt1Filter: varchar("fxt1_filter", { length: 255 }),
	fxt2WindowMode: varchar("fxt2_window_mode", { length: 255 }),
	fxt2Filter: varchar("fxt2_filter", { length: 255 }),
	isUpdated: varchar("is_updated", { length: 255 }),
});

export const cycle1AntiTooProposal = pgTable("cycle1_anti_too_proposal", {
	proposalId: integer("proposal_id").primaryKey().notNull(),
	proposalNo: text("proposal_no"),
	no: integer(),
	piName: text("pi_name"),
	obsType: text("obs_type"),
	anticipatedToo: boolean("anticipated_too"),
	stp: integer(),
	category: text(),
	groupName: text("group_name"),
	observationsNumber: integer("observations_number"),
	totalExposureTime: integer("total_exposure_time"),
	exposureUnit: text("exposure_unit"),
	sourcePriority: text("source_priority"),
});

export const wxteffdaily = pgTable("wxteffdaily", {
	recordDate: date("record_date").primaryKey().notNull(),
	wxtStatus01Count: integer("wxt_status_01_count"),
	wxtStatus02Count: integer("wxt_status_02_count"),
	wxtStatus03Count: integer("wxt_status_03_count"),
	wxtStatus04Count: integer("wxt_status_04_count"),
	wxtStatus05Count: integer("wxt_status_05_count"),
	wxtStatus06Count: integer("wxt_status_06_count"),
	wxtStatus07Count: integer("wxt_status_07_count"),
	wxtStatus08Count: integer("wxt_status_08_count"),
	wxtStatus09Count: integer("wxt_status_09_count"),
	wxtStatus10Count: integer("wxt_status_10_count"),
	wxtStatus11Count: integer("wxt_status_11_count"),
	wxtStatus12Count: integer("wxt_status_12_count"),
});

export const gpCycle2Proposal = pgTable("gp_cycle2_proposal", {
	id: serial().primaryKey().notNull(),
	no: varchar({ length: 255 }),
	proposalNo: varchar("proposal_no", { length: 255 }),
	pi: varchar({ length: 255 }),
	title: text(),
	stp: varchar({ length: 255 }),
	secondsR: varchar("seconds_r", { length: 255 }),
	obsType: varchar("obs_type", { length: 255 }),
	anticipatedToo: varchar("anticipated_too", { length: 255 }),
	userGroup: varchar("user_group", { length: 255 }),
	category: varchar({ length: 255 }),
	institution: varchar({ length: 255 }),
	ihepOrNaoc: varchar("ihep_or_naoc", { length: 255 }),
});

export const obsAutoFollowup = pgTable("obs_auto_followup", {
	id: serial().primaryKey().notNull(),
	wpProducer: varchar("wp_producer", { length: 255 }),
	wpFilename: varchar("wp_filename", { length: 255 }),
	wpId: varchar("wp_id", { length: 255 }),
	wpType: varchar("wp_type", { length: 255 }),
	wpUrgency: varchar("wp_urgency", { length: 255 }),
	obsType: varchar("obs_type", { length: 255 }),
	obsIdNumber: varchar("obs_id_number", { length: 255 }),
	obtId: varchar("obt_id", { length: 255 }),
	epDbObjectId: varchar("ep_db_object_id", { length: 255 }),
	sourceName: varchar("source_name", { length: 255 }),
	rightAscension: varchar("right_ascension", { length: 255 }),
	declination: varchar({ length: 255 }),
	requestedObsDurationInSeconds: varchar("requested_obs_duration_in_seconds", { length: 255 }),
	userName: varchar("user_name", { length: 255 }),
	cmr: varchar({ length: 255 }),
	x: varchar({ length: 255 }),
	y: varchar({ length: 255 }),
	configParameterSwitch: varchar("config_parameter_switch", { length: 255 }),
	configForceSwitch: varchar("config_force_switch", { length: 255 }),
	operationCode3: varchar("operation_code3", { length: 255 }),
	minnsigmaDim: varchar("minnsigma_dim", { length: 255 }),
	snDim: varchar("sn_dim", { length: 255 }),
	snWindows: varchar("sn_windows", { length: 255 }),
	processSwitchA: varchar("process_switch_a", { length: 255 }),
	observationModeA: varchar("observation_mode_a", { length: 255 }),
	filterA: varchar("filter_a", { length: 255 }),
	processSwitchB: varchar("process_switch_b", { length: 255 }),
	observationModeB: varchar("observation_mode_b", { length: 255 }),
	filterB: varchar("filter_b", { length: 255 }),
	tcProgrammingMode: varchar("tc_programming_mode", { length: 255 }),
	startDate: varchar("start_date", { length: 255 }),
	endDate: varchar("end_date", { length: 255 }),
	obsGspIdStart: varchar("obs_gsp_id_start", { length: 255 }),
	obsGspIdEnd: varchar("obs_gsp_id_end", { length: 255 }),
	pointingDurationInOrbits: varchar("pointing_duration_in_orbits", { length: 255 }),
	pointingDurationInSeconds: varchar("pointing_duration_in_seconds", { length: 255 }),
	payloadRightAscension: varchar("payload_right_ascension", { length: 255 }),
	payloadDeclination: varchar("payload_declination", { length: 255 }),
	qc: varchar({ length: 255 }),
	q1: varchar({ length: 255 }),
	q2: varchar({ length: 255 }),
	q3: varchar({ length: 255 }),
	angZJ2000Rgrf: varchar("ang_z_j2000_rgrf", { length: 255 }),
	angXJ2000Rgrf: varchar("ang_x_j2000_rgrf", { length: 255 }),
	angYJ2000Rgrf: varchar("ang_y_j2000_rgrf", { length: 255 }),
	obsId: varchar("obs_id", { length: 255 }),
	proposalId: varchar("proposal_id", { length: 255 }),
	sourceId: varchar("source_id", { length: 255 }),
	mainType: varchar("main_type", { length: 255 }),
	subPriority: varchar("sub_priority", { length: 255 }),
});

export const gpCycle2 = pgTable("gp_cycle2", {
	id: serial().primaryKey().notNull(),
	tdicId: varchar("tdic_id", { length: 255 }),
	sourceId: varchar("source_id", { length: 255 }),
	proposalId: varchar("proposal_id", { length: 255 }),
	proposalNo: varchar("proposal_no", { length: 255 }),
	pi: varchar({ length: 255 }),
	userGroup: varchar("user_group", { length: 255 }),
	sourceName: varchar("source_name", { length: 255 }),
	obsType: varchar("obs_type", { length: 255 }),
	ra: varchar({ length: 255 }),
	dec: varchar({ length: 255 }),
	totalExposureTime: varchar("total_exposure_time", { length: 255 }),
	exposureTimeUnit: varchar("exposure_time_unit", { length: 255 }),
	continousExposure: varchar("continous_exposure", { length: 255 }),
	visitNumber: varchar("visit_number", { length: 255 }),
	exposurePerVistMin: varchar("exposure_per_vist_min", { length: 255 }),
	exposurePerVistMax: varchar("exposure_per_vist_max", { length: 255 }),
	completeness: varchar({ length: 255 }),
	cadence: varchar({ length: 255 }),
	cadenceUnit: varchar("cadence_unit", { length: 255 }),
	precision: varchar({ length: 255 }),
	precisionUnit: varchar("precision_unit", { length: 255 }),
	startTime: varchar("start_time", { length: 255 }),
	endTime: varchar("end_time", { length: 255 }),
	sourcePriority: varchar("source_priority", { length: 255 }),
	fxt1WindowMode: varchar("fxt1_window_mode", { length: 255 }),
	fxt1Filter: varchar("fxt1_filter", { length: 255 }),
	fxt2WindowMode: varchar("fxt2_window_mode", { length: 255 }),
	fxt2Filter: varchar("fxt2_filter", { length: 255 }),
	isUpdated: varchar("is_updated", { length: 255 }),
	anticipatedToo: varchar("anticipated_too", { length: 255 }),
	stp: varchar({ length: 255 }),
	category: varchar({ length: 255 }),
	type: varchar({ length: 255 }),
	payload: varchar({ length: 255 }).default(''),
	wxtCmos: varchar("wxt_cmos", { length: 255 }).default(''),
	cmosX: varchar("cmos_x", { length: 255 }).default(''),
	cmosY: varchar("cmos_y", { length: 255 }).default(''),
	fxtCmr: varchar("fxt_cmr", { length: 255 }).default(''),
	cmrX: varchar("cmr_x", { length: 255 }).default(''),
	cmrY: varchar("cmr_y", { length: 255 }).default(''),
});
