import { boolean, integer, pgTable, varchar } from "drizzle-orm/pg-core";

export const usersTable = pgTable("users", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  name: varchar({ length: 255 }).notNull(),
  age: integer().notNull(),
  email: varchar({ length: 255 }).notNull().unique(),
  vip: boolean().notNull().default(false),
});

export const tooReqTable = pgTable("too_req", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  request_filename: varchar({ length: 255 }),
  request_date: varchar({ length: 255 }),
  request_urgency: varchar({ length: 255 }),
  obs_type: varchar({ length: 255 }),
  ep_db_object_id: varchar({ length: 255 }),
  source_name: varchar({ length: 255 }),
  right_ascension: varchar({ length: 255 }),
  declination: varchar({ length: 255 }),
  requested_obs_duration_in_seconds: integer().notNull().default(0),
  requested_obs_duration_in_orbits: integer().notNull().default(0),
  user_name: varchar({ length: 255 }),
  user_group: varchar({ length: 255 }),
  cmr: varchar({ length: 255 }),
  x: varchar({ length: 255 }),
  y: varchar({ length: 255 }),
  process_switch_a: varchar({ length: 255 }),
  observation_mode_a: varchar({ length: 255 }),
  filter_a: varchar({ length: 255 }),
  process_switch_b: varchar({ length: 255 }),
  observation_mode_b: varchar({ length: 255 }),
  filter_b: varchar({ length: 255 }),
  obs_priority: varchar({ length: 255 }),
  time_constraints: varchar({ length: 255 }),
  source_id: integer().notNull().default(0),
  proposal_id: integer().notNull().default(0),
  proposal_no: integer().notNull().default(0),
  toToo: boolean().notNull().default(false),
});